server/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/update/', views.update, name='update'),
]

server/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('register_dog.urls')),
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
]

server/register_dog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'register_dog'

urlpatterns = [
    path('', views.main1, name='main1'),
    path('main2/', views.main2, name='main2'),
    path('create_post_lost/', views.LostCreate.as_view(), name="create_post_lost"),
    path('create_post_found/', views.FoundCreate.as_view(), name="create_post_found"),
    path('mypage/', views.mypage, name="mypage"),
    path('imageresult/', views.imageresult, name="imageresult"),
    path('textresult/', views.textresult, name="textresult"),
    path('detail/<int:pk>/', views.detail, name="detail"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/register_dog/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    category_choices = (('등록', '실종견 등록'), ('제보', '목격/구조 제보'))
    category_name = models.CharField('카테고리(등록/제보)*', max_length=15, unique=True, choices=category_choices)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = 'Categories'

class Dog_post(models.Model):
    post_title = models.CharField('글 제목*', max_length=100, default='')

    category = models.ForeignKey(Category, verbose_name='카테고리(등록/제보)*', on_delete=models.CASCADE)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    dog_name = models.CharField('실종견 이름', max_length=15, null=True, blank=True)
    breed = models.CharField('견종', max_length=40, null=True, blank=True)

    location_city_choices = (('서울', '서울특별시'), ('부산', '부산광역시'),
                             ('대구', '대구광역시'), ('인천', '인천광역시'),
                             ('광주', '광주광역시'), ('대전', '대전광역시'),
                             ('울산', '울산광역시'), ('경기', '경기도'),
                             ('강원', '강원도'), ('충북', '충청북도'),
                             ('충남', '충청남도'), ('전북', '전라북도'),
                             ('전남', '전라남도'), ('경북', '경상북도'),
                             ('경남', '경상남도'), ('세종', '세종특별자치시'),
                             ('제주', '제주특별자치도'))
    location_city = models.CharField('위치(시/도)*', max_length=10, choices=location_city_choices)

    location_detail = models.CharField('위치(세부 설명)', max_length=100, null=True, blank=True)
    date = models.DateField('날짜(YYYY-MM-DD)*', default=datetime.datetime.now())

    sex_choices = (('암컷', '암컷'), ('수컷', '수컷'), ('모름', '모름'))
    sex = models.CharField('성별', max_length=10, null=True, blank=True, choices=sex_choices)

    age = models.CharField('나이', max_length=10, null=True, blank=True)
    reward = models.CharField('사례금', max_length=20, null=True, blank=True)

    description = models.CharField('기타 특징*', max_length=300, default='')

    image1 = models.ImageField('사진1', null=True, blank=True)
    image2 = models.ImageField('사진2', null=True, blank=True)
    image3 = models.ImageField('사진3', null=True, blank=True)

    def __str__(self):
        return f'{self.post_title} :: {self.category}'

    def get_ablolute_url(self):
        return '/post/{}/'.format(self.pk)

class Uploaded_Image(models.Model):
    uploaded_image = models.ImageField(upload_to='images/0000', null=True, blank=True)

server/register_dog/forms.py
from django import forms

from .models import Uploaded_Image


class UploadedImageForm(forms.ModelForm):
    class Meta:
        model = Uploaded_Image
        fields = ['uploaded_image']
        labels = {
            'uploaded_image' : '이미지 업로드'
        }
        

server/register_dog/views.py
import os
import numpy as np
import skimage as sk
import matplotlib.pyplot as plt
import matplotlib.image as img
from tqdm import tqdm_notebook

import requests
import cv2
from sklearn.cluster import KMeans
import tensorflow as tf
import keras
import keras.backend as K
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render, redirect, get_object_or_404

from .forms import UploadedImageForm
#from . import clustering
from .models import Dog_post, Category, Uploaded_Image
#from .server.register_dog import forms
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from sentence_transformers import SentenceTransformer, util
import torch

def main1(request):
    posts = Dog_post.objects.filter(category=1)

    return render(
        request,
        'register_dog/main1.html',
        {
            'posts': posts,
        }
    )

def main2(request):
    posts = Dog_post.objects.filter(category=2)

    return render(
        request,
        'register_dog/main2.html',
        {
            'posts': posts,
        }
    )

# 보호자가 실종견 등록
class LostCreate(LoginRequiredMixin, CreateView):
    model = Dog_post

    fields = ['post_title', 'category', 'dog_name', 'breed', 'location_city',
              'location_detail', 'date', 'sex', 'age', 'reward', 'description',
              'image1', 'image2', 'image3']
    template_name = 'register_dog/dog_post_lost_form.html'
    success_url = '/create_post_lost/'

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(LostCreate, self).form_valid(form)
        else:
            return redirect('/create_post_lost/')

# 실종견 제보
class FoundCreate(LoginRequiredMixin, CreateView):
    model = Dog_post
    fields = ['post_title', 'category', 'breed', 'location_city',
              'location_detail', 'date', 'sex', 'description',
              'image1', 'image2', 'image3']

    template_name = 'register_dog/dog_post_found_form.html'
    success_url = '/create_post_found/'

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(FoundCreate, self).form_valid(form)
        else:
            return redirect('/create_post_found/')

# 이미지 파일 저장 경로 변경
@receiver(post_save, sender=Dog_post)
def update_image_path(sender, instance, created, **kwargs):
    if created:
        if instance.image1:
            image1_path = f'images/{str(instance.pk).zfill(4)}/{instance.image1.name}'
            full_image1_path = os.path.join(settings.MEDIA_ROOT, image1_path)
            os.makedirs(os.path.dirname(full_image1_path), exist_ok=True)
            instance.image1.storage.save(full_image1_path, instance.image1)
            instance.image1.name = image1_path

        if instance.image2:
            image2_path = f'images/{str(instance.pk).zfill(4)}/{instance.image2.name}'
            full_image2_path = os.path.join(settings.MEDIA_ROOT, image2_path)
            os.makedirs(os.path.dirname(full_image2_path), exist_ok=True)
            instance.image2.storage.save(full_image2_path, instance.image2)
            instance.image2.name = image2_path

        if instance.image3:
            image3_path = f'images/{str(instance.pk).zfill(4)}/{instance.image3.name}'
            full_image3_path = os.path.join(settings.MEDIA_ROOT, image3_path)
            os.makedirs(os.path.dirname(full_image3_path), exist_ok=True)
            instance.image3.storage.save(full_image3_path, instance.image3)
            instance.image3.name = image3_path

        instance.save()

def mypage(request):
    posts = Dog_post.objects.all()

    return render(
        request,
        'register_dog/mypage.html',
        {
            'posts': posts,
        }
    )

# Loss definition
alpha = 0.3
def triplet(y_true, y_pred):
    a = y_pred[0::3]
    p = y_pred[1::3]
    n = y_pred[2::3]

    ap = K.sum(K.square(a-p), -1)
    an = K.sum(K.square(a-n), -1)

    return K.sum(tf.nn.relu(ap-an+alpha))

# Metric definition
def triplet_acc(y_true, y_pred):
    a = y_pred[0::3]
    p = y_pred[1::3]
    n = y_pred[2::3]

    ap = K.sum(K.square(a - p), -1)
    an = K.sum(K.square(a - n), -1)

    return K.less(ap+alpha, an)

def imageresult(request):
    if (request.method == 'POST'):
        uploaded_image_model = Uploaded_Image()
        uploaded_image_model.uploaded_image = request.FILES.get('image_upload')
        uploaded_image_model.save()

    PATH = 'C:\\rovemin\\POOM\\server\\media\\images'
    filenames = []
    labels = []
    idx = 0
    SIZE = (224,224,3)

    for path, dirs, files in os.walk(PATH):
        if len(files) > 0:
            if len(files) > 0:
                for file in files:
                    file_path = os.path.join(path, file)
                    filenames.append(file_path)
            labels = np.append(labels, np.ones(len(files))*idx)
            idx += 1

    h, w, c = SIZE
    images = np.empty((len(filenames), h, w, c))
    for i, f in enumerate(filenames):
        images[i] = sk.io.imread(f)

    # Normalization
    images /= 255.0

    # 게시물 폴더 개수
    nbof_classes = len(np.unique(labels))

    # loss definition
    alpha = 0.3

    def triplet(y_true, y_pred):

        a = y_pred[0::3]
        p = y_pred[1::3]
        n = y_pred[2::3]

        ap = K.sum(K.square(a - p), -1)
        an = K.sum(K.square(a - n), -1)

        return K.sum(tf.nn.relu(ap - an + alpha))

    # metric definition
    def triplet_acc(y_true, y_pred):
        a = y_pred[0::3]
        p = y_pred[1::3]
        n = y_pred[2::3]

        ap = K.sum(K.square(a - p), -1)
        an = K.sum(K.square(a - n), -1)

        return K.less(ap + alpha, an)

    # 모델 정의
    model = tf.keras.models.load_model('C:\\rovemin\\POOM\\server\\model\\2023.04.30.dogfacenet.146.h5',
                                       custom_objects={'triplet': triplet, 'triplet_acc': triplet_acc})

    mod = tf.keras.Model(model.layers[0].input, model.layers[-1].output)
    predict = mod.predict(images)
    kmeans = KMeans(n_clusters=len(np.unique(labels)), max_iter=2000, random_state=0, tol=0.2).fit(predict)

    images_cluster = [images[np.equal(kmeans.labels_, i)] for i in range(len(labels))]
    labels_cluster = [labels[np.equal(kmeans.labels_, i)] for i in range(len(labels))]

    # 임시로 input 이미지 지정해서 시험해보기
    input_image = 'POOM/server/media/images/0000/img1.jpg'
    input_image_split = input_image.split('/')
    input_image_folder = int(input_image_split[4])

    clustering_num = []

    for i in range(len(labels_cluster)):
        if input_image_folder in labels_cluster[i]:
            clustering_num.append(i)

    return render(
        request,
        'register_dog/imageresult.html',
        {
            'clustering_num': clustering_num.append(i)
        }
    )

model2 = SentenceTransformer("Huffon/sentence-klue-roberta-base")
def textresult(request):
    docs = list(Dog_post.objects.values('description'))
    document_embeddings = model2.encode(docs)

    query = request.POST['text_search']
    query_embedding = model2.encode(query)

    top_k = min(5, len(docs))

    # 입력 문장 - 문장 후보군 간 코사인 유사도 계산
    cos_scores = util.pytorch_cos_sim(query_embedding, document_embeddings)[0]

    # 코사인 유사도 순으로 'top_k' 개 문장 추출
    top_results = torch.topk(cos_scores, k=top_k)
    results = []
    results_idx = []

    numbers = []

    # result = enumerate(zip(top_results[0], top_results[1]))
    for i, (score, idx) in enumerate(zip(top_results[0], top_results[1])):
        result = docs[idx]

        results_idx.append(idx.item()+1)
        results.append(result['description'])

    print_result = list(zip(results_idx, results))

    for i in range(top_k):
        numbers.append(i)

    return render(
        request,
        'register_dog/textresult.html',
        {
            'print_result':print_result,
        }
    )

def detail(request, pk):
    post = Dog_post.objects.get(pk=pk)

    context = {'post': post}

    return render(
        request,
        'register_dog/detail.html',
        context
     )

def mypage(request):
    # logged_in_user = request.user
    logged_in_user_posts = Dog_post.objects.filter(author=request.user)
    return render(
        request,
        'register_dog/mypage.html',
        {
            'posts':logged_in_user_posts,
        }
    )

server/register_dog/templates/register_dog/dog_post_found_form.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="description" content="POOM">
  <title>POOM</title>
  <link rel="stylesheet" href="{% static 'register_dog/lost.css' %}" media="screen" type="text/css"/>
</head>

<body>

  <!--헤더-->
  <div class="nav">
    <a href="{% url 'register_dog:main1' %}">
      <img src="{% static 'logo/logo2.png' %}" title="logo" />
    </a>
    <div class="nav-items">

      {% if user.is_authenticated %}
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_lost' %}'">실종견 등록하기</button>
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_found' %}'">목격/구조 제보하기</button>
      {% endif %}

      {% if user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
      {% else %}
      <a class="nav-item" href="{% url 'common:login' %}">로그인</a>
      {% endif %}

      {% if user.is_authenticated %}
      <div class="nav-item" onclick="location.href='{% url 'register_dog:mypage' %}'">마이페이지 </div>
      {% endif %}

      {% if not user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:signup' %}">회원가입</a>
      {% endif %}
    </div>
  </div>

  <!--입력폼-->
  <div class="box">실종견 제보</div>
  <div class="background">
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
      <table class="table1">
        {{ form }}
      </table>

      <button type="submit" class="but1">등록하기</button>
    </form>
  </div>

</body>

</html>

server/register_dog/templates/register_dog/dog_post_lost_form.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="description" content="POOM">
  <title>POOM</title>
  <link rel="stylesheet" href="{% static 'register_dog/lost.css' %}" media="screen" type="text/css"/>
</head>

<body>

  <!--헤더-->
  <div class="nav">
    <a href="{% url 'register_dog:main1' %}">
      <img src="{% static 'logo/logo2.png' %}" title="logo" />
    </a>
    <div class="nav-items">

      {% if user.is_authenticated %}
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_lost' %}'">실종견 등록하기</button>
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_found' %}'">목격/구조 제보하기</button>
      {% endif %}

      {% if user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
      {% else %}
      <a class="nav-item" href="{% url 'common:login' %}">로그인</a>
      {% endif %}

      {% if user.is_authenticated %}
      <div class="nav-item" onclick="location.href='{% url 'register_dog:mypage' %}'">마이페이지 </div>
      {% endif %}

      {% if not user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:signup' %}">회원가입</a>
      {% endif %}
    </div>
  </div>

  <!--입력폼-->
  <div class="box">실종견 등록</div>
  <div class="background">
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
      <table class="table1">
        {{ form }}
      </table>

      <button type="submit" class="but1">등록하기</button>
    </form>
  </div>

</body>

</html>

server/register_dog/templates/register_dog/imageresult.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="description" content="POOM">
  <title>POOM</title>
  <link href="{% static 'register_dog/imageresult.css' %}" rel="stylesheet" type="text/css" />
</head>

<body>

  <!--헤더-->
  <div class="nav">
    <a href="{% url 'register_dog:main1' %}">
      <img src="{% static 'logo/logo2.png' %}" title="logo" />
    </a>
    <div class="nav-items">

      {% if user.is_authenticated %}
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_lost' %}'">실종견 등록하기</button>
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_found' %}'">목격/구조 제보하기</button>
      {% endif %}

      <div class="nav-item" onclick="location.href='{% url 'register_dog:main1' %}'">Home</div>
      {% if user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
      {% else %}
      <a class="nav-item" href="{% url 'common:login' %}">로그인</a>
      {% endif %}

      {% if user.is_authenticated %}
      <div class="nav-item" onclick="location.href='{% url 'register_dog:mypage' %}'">마이페이지 </div>
      {% endif %}

      {% if not user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:signup' %}">회원가입</a>
      {% endif %}
    </div>
  </div>

  <!--검색바-->
  <div class="search_box">
    <button class="sbut2">이미지 검색</button>

    <form  action="{% url 'register_dog:imageresult' %}" method="POST">
      {% csrf_token %}
      <input name="text_search" class="search" type="text" placeholder="실종견 검색">

    </form>
    <button class="sbut" type="submit">검색</button>

  </div>

  <!--검색결과창-->
  <div class="resultbar">
    <div class="imageresult"> 이미지 검색 결과 </div>
  </div>

  <!--리스트-->
  <div class="searchcontainer">
    <div class="dog_list">
        {% for i in clustering_num %}
            <p>{{ i }}</p>
            <img src="{{ i }}">
        {% endfor %}
    </div>
  </div>

</body>

</html>

server/register_dog/templates/register_dog/index.html
<!--POOM 메인 페이지-->
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>POOM main page</title>
        <link rel="stylesheet" href="{% static 'register_dog/bootstrap/bootstrap.min.css' %}" media="screen">
        <style>
            nav {background-color: darkgreen; font-size: 150%; text-align: center}
            nav a {color:gold}
        </style>
    </head>
    <body>
        <nav>
            <a href="./registerDog.html">실종견 등록하기</a>
            <a href="./registerDog.html">목격/구조 제보하기</a>
        </nav>

        <h1>POOM</h1>

        {% for p in posts %}
            <hr/>
            <h2>{{ p.dog_name }}</h2>
            <h2>{{ p.category }}</h2>
            <h4>{{ p.location_city }}</h4>
            <p>{{ p.description }}</p>
            {% if p.image1 %}
                <img src="{{ p.image1.url }}" style="width:100px; height:100px">
            {% endif %}
        {% endfor %}

    </body>
</html>

server/register_dog/templates/register_dog/main1.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="description" content="POOM">
  <title>POOM</title>
  <link href="{% static 'register_dog/main1.css' %}" rel="stylesheet" type="text/css" />
</head>

<body>

  <!--헤더-->
  <div class="nav">
    <a href="{% url 'register_dog:main1' %}">
      <img src="{% static 'logo/logo2.png' %}" title="logo" />
    </a>
    <div class="nav-items">
      {% if user.is_authenticated %}
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_lost' %}'">실종견 등록하기</button>
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_found' %}'">목격/구조 제보하기</button>
      {% endif %}

      {% if user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
      {% else %}
      <a class="nav-item" href="{% url 'common:login' %}">로그인</a>
      {% endif %}

      {% if user.is_authenticated %}
      <div class="nav-item" onclick="location.href='{% url 'register_dog:mypage' %}'">마이페이지 </div>
      {% endif %}

      {% if not user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:signup' %}">회원가입</a>
      {% endif %}
    </div>
  </div>

  <!--검색바-->
  <div class="search_box">
    <div class="image_search_box">
      <button class="sbut2" id="modal_btn">이미지 검색</button>
      <div class="black_bg"></div>
      <div class="modal_wrap">
        <div class="modal_close"><a href="#">close</a></div>
        <div class="popupbar"> 이미지로 검색하기 </div>
        <form action="{% url 'register_dog:image' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="upload-form">
            <label for="file">
              <input name="image_upload" type="file" id="file" class="btn-upload">
            </label>
          </div>
          <div class="mpbut">
            <button type="submit" class="but4" onclick="location.href='{% url 'register_dog:imageresult' %}'">검색 시작!</button>
          </div>
        </form>
          <div class="discr">
          반려견의 얼굴이 잘 드러나는 사진을 업로드해주세요 <br>
          마이페이지에서는 이미 등록된 반려견을 검색할 수 있습니다!
        </div>
      </div>
    </div>

    <form  action="{% url 'register_dog:textresult' %}" method="POST">
      {% csrf_token %}
      <input name="text_search" class="search" type="text" placeholder="실종견 검색">
      <button class="sbut" type="submit">검색</button>
    </form>
  </div>

  <!--리스트 설명-->
  <div class="mainlist">
    <div class="lost_list" onclick="location.href='{% url 'register_dog:main1' %}'"> 실종 신고 목록</div>
    <div class="found_list" onclick="location.href='{% url 'register_dog:main2' %}'"> 제보 목록 </div>
  </div>

  <!--리스트-->
  <div class=" container">
    <div class="dog_list">
      {% if posts.exists %}
        {% for p in posts %}
        <div class="card" style="cursor:pointer;" onclick="location.href='/detail/{{ p.pk }}/'">
          <div class="image">
            <img src="{{ p.image1.url }}" alt="{{ p }}">
          </div>
          <div class="text">
            <h3>{{ p.post_title }}</h3>
            <p>by {{ p.author | upper }}</p>
            <p>지역: {{ p.location_city }}</p>
            <p>내용: {{ p.description | truncatewords:3 }}</p>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <h3 class="text">아직 게시물이 없습니다.</h3>
      {% endif %}
    </div>
  </div>

</body>

<script>
  window.onload = function () {

    function onClick() {
      document.querySelector('.modal_wrap').style.display = 'block';
      document.querySelector('.black_bg').style.display = 'block';
    }
    function offClick() {
      document.querySelector('.modal_wrap').style.display = 'none';
      document.querySelector('.black_bg').style.display = 'none';
    }

    document.getElementById('modal_btn').addEventListener('click', onClick);
    document.querySelector('.modal_close').addEventListener('click', offClick);
  };
</script>

</html>

server/register_dog/templates/register_dog/main2.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="description" content="POOM">
  <title>POOM</title>
  <link href="{% static 'register_dog/main2.css' %}" rel="stylesheet" type="text/css" />
</head>

<body>

  <!--헤더-->
  <div class="nav">
    <a href="{% url 'register_dog:main1' %}">
      <img src="{% static 'logo/logo2.png' %}" title="logo" />
    </a>
    <div class="nav-items">

      {% if user.is_authenticated %}
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_lost' %}'">실종견 등록하기</button>
      <button type="button" class="but" onclick="location.href='{% url 'register_dog:create_post_found' %}'">목격/구조 제보하기</button>
      {% endif %}

      {% if user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
      {% else %}
      <a class="nav-item" href="{% url 'common:login' %}">로그인</a>
      {% endif %}

      {% if user.is_authenticated %}
      <div class="nav-item" onclick="location.href='{% url 'register_dog:mypage' %}'">마이페이지 </div>
      {% endif %}

      {% if not user.is_authenticated %}
      <a class="nav-item" href="{% url 'common:signup' %}">회원가입</a>
      {% endif %}
    </div>
  </div>

  <!--검색바-->
  <div class="search_box">
    <div class="image_search_box">
      <button class="sbut2" id="modal_btn">이미지 검색</button>
      <div class="black_bg"></div>
      <div class="modal_wrap">
        <div class="modal_close"><a href="#">close</a></div>
        <div class="popupbar"> 이미지로 검색하기 </div>
        <form action="{% url 'register_dog:image' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="upload-form">
            <label for="file">
              <input name="image_upload" type="file" id="file" class="btn-upload">
            </label>
          </div>
          <div class="mpbut">
            <button type="submit" class="but4" onclick="location.href='{% url 'register_dog:imageresult' %}'">검색 시작!</button>
          </div>
        </form>
          <div class="discr">
          반려견의 얼굴이 잘 드러나는 사진을 업로드해주세요 <br>
          마이페이지에서는 이미 등록된 반려견을 검색할 수 있습니다!
        </div>
      </div>
    </div>

    <form action="{% url 'register_dog:textresult' %}" method="POST">
      {% csrf_token %}
      <input name="text_search" class="search" type="text" placeholder="실종견 검색">
      <button class="sbut" type="submit">검색</button>
    </form>
  </div>

  <!--리스트 설명-->
  <div class="mainlist">
    <div class="lost_list" onclick="location.href='{% url 'register_dog:main1' %}'"> 실종 신고 목록</div>
    <div class="found_list" onclick="location.href='{% url 'register_dog:main2' %}'"> 제보 목록 </div>
  </div>

  <!--리스트-->
  <div class=" container">
    <div class="dog_list">
      {% if posts.exists %}
        {% for p in posts %}
        <div class="card" style="cursor:pointer;" onclick="location.href='/detail/{{ p.pk }}/'">
          <div class="image">
            {% if p.image1.url != None %}
              <img src="{{ p.image1.url }}" alt="{{ p }}">
            {% else %}
              <img src="{% static 'logo/blank.png' %}">
            {% endif %}
          </div>
          <div class="text">
            <h3>{{ p.post_title }}</h3>
            <p>by {{ p.author | upper }}</p>
            <p>지역: {{ p.location_city }}</p>
            <p>내용: {{ p.description | truncatewords:3 }}</p>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <h3 class="text">아직 게시물이 없습니다.</h3>
      {% endif %}
    </div>
  </div>

</body>

<script>
  window.onload = function () {

    function onClick() {
      document.querySelector('.modal_wrap').style.display = 'block';
      document.querySelector('.black_bg').style.display = 'block';
    }
    function offClick() {
      document.querySelector('.modal_wrap').style.display = 'none';
      document.querySelector('.black_bg').style.display = 'none';
    }

    document.getElementById('modal_btn').addEventListener('click', onClick);
    document.querySelector('.modal_close').addEventListener('click', offClick);
  };
</script>

</html>